services:
  db:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_DB: clevbill_db
      POSTGRES_USER: clevbill
      POSTGRES_PASSWORD: clevbill
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
